### ISSUE TITLE
CMake - use ${CMAKE_CURRENT_SOURCE_DIR} instead of ${CMAKE_SOURCE_DIR}

### ISSUE THREAD

**Issue by waj334** [stohrendorf/libjpeg-cmake#1]
I changed line 44 in CMakeLists.txt to:

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/jconfig.h.in ${CMAKE_CURRENT_SOURCE_DIR}/jconfig.h)

Otherwise, it'll look for the .in file in the wrong directory when added as a subdirectory.

**Comment by stohrendorf** [comment]
Thanks for reporting, and also for being the first person reporting an issue in one of my projects ;)
